### ISSUE TITLE
curl_init() wrong validation for PHP 8+

### ISSUE THREAD

**Issue by pveiga2** [cashlink/bav#8]
### Problem:
I was getting exceptions when running the ->update()  method on a FileDataBackend,
and noticed the error comes from " new Downloader() "

What happens is the  **malkusch\bav\Downloader**  constructor will check if curl_init() returns a Resource.
However, after PHP8, curl_init() returns an instance of CurlHandle which does not evaluate as a resource, and it causes this constructor to always throw a DownloaderException.

### Suggestion: 
Maybe instead of checking is_resource() , you could just check for strict false, which would be returned by curl_init() on error.
`$this->handle = curl_init();`
` if ($this->handle === false) {
        throw new DownloaderException("Failed initializing curl");
  }
`

**Comment by mensler** [comment]
Thanks for reporting, I created a new release to fix this.
Please be aware that this is a new major release (4.0.0) because of the new PHP version requirement (>= 7.3).
